### ISSUE TITLE
is this dead ?

### ISSUE THREAD

**Issue by amiracam** [astroband/ruby-stellar-sdk#2]
I see nothing posted since last year ? better use JSON rpc ?

**Comment by nullstyle** [comment]
For the most part, yes it is.  We don't use ruby very much here anymore at stellar (mostly just a couple of dashboards and tools) and so this library doesn't get much love.  I'll add a note to the README that says we're looking for a more active maintainer.

**Comment by ankurp** [comment]
@nullstyle I do not mind maintaining this repo and would appreciate access to be part of the Stellar team so I can merge PRs. I have submitted PRs to fix the docs and examples code and next plan on implementing friendbot.

**Comment by nullstyle** [comment]
Hi @ankurp,

After thinking this issue over some more I'm reluctant to pass off control of this repo to an outside party.  I've had a couple of people approach me now about taking over maintainership of this project and I've come to the conclusion that I'm not happy turning over control of this repo or the `stellar-sdk` and `stellar-base` names on rubygems. Instead, I would rather you fork the repo to another gem name and I can post a notice and a link for people who find this repo and are looking for the most actively maintained project.

Given the sensitive nature of code that interacts with the stellar network, It is risky handing over ownership of that code because an unscrupulous engineer could do serious damage.  While these libraries are not heavily used (~ 30k downloads for `stellar-base`) I'm still not comfortable exposing developers who have trusted this repo in the past to the risk of a new maintainer in the future.  I'd rather that trust be rebuilt at a new repo if I'm not going to be super involved in reviewing every inclusion into the codebase.   

I'm going to close this issue but I am happy to continue the discussion here if you have questions or concerns.  Luckily bundler is great and the ruby community is pretty tolerant of creative names (see `nokogiri` as an example) so the fact that you'll need to change names shouldn't be a huge deterrent to gaining adoption.
