### ISSUE TITLE
Implementation for Create Account

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [astroband/ruby-stellar-sdk#24]
```
begin
             client  = Stellar::Client.default_testnet()
            client.create_account({
              funder:           Stellar::Account.random(),
              account:          Stellar::Account.random(),
              starting_balance: 10_000_000 * Stellar::ONE,
              sequence: 1,
            })
            puts friendbot.address
        rescue Exception => e
            puts  "Error: #{e.message}"
        end

Give us :
`Error: the server responded with status 400`

Any advice? Regards
```

**Comment by rahulpuroht** [comment]
Still facing same error.

**Comment by ramontayag** [comment]
Check out `spec/lib/stellar/client_spec.rb` -- there's an integration test here that hits the Horizon server. I also just re-recorded it locally and it works fine.

I suspect it's because the sequence you're using should not be `1`. I know that this is the example given in `examples/06_fund_testnet_friendbot.rb`. Eventually, the examples should be integration specs.

**Comment by ramontayag** [comment]
@bartekn mind closing this? I think it has been resolved.
